### ISSUE TITLE
[Feature Request] Supply a systemd Script for Linux (Steam Deck)

### ISSUE THREAD

**Issue by NightHammer1000** [Radiicall/steam-presence-on-discord#1]
As the /etc folder on the Steam Deck is not part of the Read Only File system, We can make this tool run on boot in the Background, automatically updating the Status for everything we play.

Only thing we need is a systemd script we can either config or symlink to /etc/systemd/system and enable it.

**Comment by justradical** [comment]
This needs to be run on a computer with discord installed, the point of it is to be ran on a second computer or a server so the steamdeck isnt using resources on discord. I can try helping with the systemd script but i would not recommend running this and discord on the steamdeck itself.

**Comment by justradical** [comment]
I added a systemd script to the newest release.
