### ISSUE TITLE
[Bug Report] **Executable doesn't look in its own directory, but for the current one**

### ISSUE THREAD

**Issue by alba4k** [Radiicall/steam-presence-on-discord#3]
**Describe the bug**
The executable doesn't look for .env in its own directory, but in the directory it is run from. This causes issues when it comes to the systemd service (which runs in the user's home).

**To Reproduce**
1. Run the executable from the directory where .env is found
2. Everything works
3. Change directory and run it again
4. It asks for a new one

**Expected behavior**
It should still see it

**Screenshots**
![immagine](https://user-images.githubusercontent.com/84153269/227655090-19725e0b-4004-45c5-b364-3fe64eb3c58f.png)

**Details:**
 - OS: Arch Linux
 - Version 1.3.0

**Additional context**
-

**Comment by justradical** [comment]
This project isnt being worked on, check out Temmie's script instead https://github.com/JustTemmie/steam-presence

**Comment by alba4k** [comment]
Yea I know about it, wanted to give this version a shot too

guess I'll use their one then, thanks for answering :)
